let items = [
  {
    id: "01",
    item_image: "/images/shoe1.png",
    rating: {
      stars: 4.5,
      noOfReviews: "14k",
    },
    comapny_name: "NIke Air jordan Excee",
    current_price: "RS 7606",
    original_price: "RS 18405",
    discount: "60%",
  },
  {
    id: "02",
    item_image: "/images/shoe2.png",
    rating: {
      stars: 4.0,
      noOfReviews: "10k",
    },
    comapny_name: "Kine six   Excee",
    current_price: "RS 8765",
    original_price: "RS 10405",
    discount: "40%",
  },
  {
    id: "03",
    item_image: "/images/shoe3.png",
    rating: {
      stars: 4.5,
      noOfReviews: 1400,
    },
    comapny_name: "NIke flex green  ",
    current_price: "RS 5246",
    original_price: "RS 7892",
    discount: "30%",
  },
  ,
  {
    id: "04",
    item_image: "/images/shoe44.png",
    rating: {
      stars: 4.5,
      noOfReviews: "8k",
    },
    comapny_name: "Addidas running",
    current_price: "RS 2558",
    original_price: "RS 4563",
    discount: "60%",
  },
  {
    id: "05",
    item_image: "/images/shoe5.png",
    rating: {
      stars: 4.5,
      noOfReviews: "6k",
    },
    comapny_name: "NIke Air jordan Excee",
    current_price: "RS 7606",
    original_price: "RS 18405",
    discount: "50%",
  },
  {
    id: "06",
    item_image: "/images/shoe6.png",
    rating: {
      stars: 4.5,
      noOfReviews: "3k",
    },
    comapny_name: "NIke  jordan Air Excee",
    current_price: "RS 7606",
    original_price: "RS 18405",
    discount: "50%",
  },
  {
    id: "07",
    item_image: "/images/shoe7.png",
    rating: {
      stars: 4.5,
      noOfReviews: 1400,
    },
    comapny_name: "NIke Air jordan Excee",
    current_price: "RS 7606",
    original_price: "RS 18405",
    discount: "60%",
  },
  {
    id: "08",
    item_image: "/images/shoe8.png",
    rating: {
      stars: 4.5,
      noOfReviews: 1400,
    },
    comapny_name: "NIke Air jordan Excee",
    current_price: "RS 7606",
    original_price: "RS 18405",
    discount: "60%",
  },
  {
    id: "09",
    item_image: "/images/shoe9.png",
    rating: {
      stars: 4.5,
      noOfReviews: 1400,
    },
    comapny_name: "NIke Air jordan Excee",
    current_price: "RS 7606",
    original_price: "RS 18405",
    discount: "60%",
  },
  {
    id: "10",
    item_image: "/images/shoe16.png",
    rating: {
      stars: 4.5,
      noOfReviews: "7k",
    },
    comapny_name: "NIke Air jordan Excee",
    current_price: "RS 7606",
    original_price: "RS 18405",
    discount: "60%",
  },
  {
    id: "11",
    item_image: "/images/shoe11.png",
    rating: {
      stars: 4.5,
      noOfReviews: "9k",
    },
    comapny_name: "NIke Air jordan Excee",
    current_price: "RS 7606",
    original_price: "RS 18405",
    discount: "60%",
  },
  {
    id: "12",
    item_image: "/images/shoe12.png",
    rating: {
      stars: 4.5,
      noOfReviews: 1400,
    },
    comapny_name: "NIke Air jordan Excee",
    current_price: "RS 7606",
    original_price: "RS 18405",
    discount: "60%",
  },
  {
    id: "13",
    item_image: "/images/shoe13.png",
    rating: {
      stars: 4.5,
      noOfReviews: 1400,
    },
    comapny_name: "NIke Air jordan Excee",
    current_price: "RS 7606",
    original_price: "RS 18405",
    discount: "60%",
  },
  {
    id: "14",
    item_image: "/images/shoe14.png",
    rating: {
      stars: 4.5,
      noOfReviews: 1400,
    },
    comapny_name: "NIke Air jordan Excee",
    current_price: "RS 7606",
    original_price: "RS 18405",
    discount: "60%",
  },
  {
    id: "15",
    item_image: "/images/shoe15.png",
    rating: {
      stars: 4.5,
      noOfReviews: 1400,
    },
    comapny_name: "NIke Air jordan Excee",
    current_price: "RS 7606",
    original_price: "RS 18405",
    discount: "60%",
  },
  {
    id: "16",
    item_image: "/images/shoe16.png",
    rating: {
      stars: 5.0,
      noOfReviews: "8k",
    },
    comapny_name: "Nike basketball shoes",
    current_price: "RS 8569",
    original_price: "RS 9520",
    discount: "20%",
  },
];
