const items = [
  {
    id: "01",
    item_image: "/images/shoe1.png",
    rating: {
      stars: 4.5,
      noOfReviews: "14k",
    },
    comapny_name: "NIke Air jordan Excee",
    current_price: 7606,
    original_price: 18405,
    discount: "60%",
  },
  {
    id: "02",
    item_image: "/images/shoe2.png",
    rating: {
      stars: 4.0,
      noOfReviews: "10k",
    },
    comapny_name: "Kine six   Excee",
    current_price: 8765,
    original_price: 10405,
    discount: "40%",
  },
  {
    id: "03",
    item_image: "/images/shoe3.png",
    rating: {
      stars: 4.5,
      noOfReviews: 1400,
    },
    comapny_name: "NIke flex green  ",
    current_price: 5246,
    original_price: 7892,
    discount: "30%",
  },
  {
    id: "04",
    item_image: "/images/shoe44.png",
    rating: {
      stars: 4.5,
      noOfReviews: "8k",
    },
    comapny_name: "Addidas running",
    current_price: 2558,
    original_price: 4563,
    discount: "60%",
  },
  {
    id: "05",
    item_image: "/images/shoe5.png",
    rating: {
      stars: 4.5,
      noOfReviews: "6k",
    },
    comapny_name: "NIke Air jordan Excee",
    current_price: 7606,
    original_price: 18405,
    discount: "50%",
  },
  {
    id: "06",
    item_image: "/images/shoe6.png",
    rating: {
      stars: 4.5,
      noOfReviews: "3k",
    },
    comapny_name: "NIke  jordan Air Excee",
    current_price: 7606,
    original_price: 18405,
    discount: "50%",
  },
  {
    id: "07",
    item_image: "/images/shoe7.png",
    rating: {
      stars: 4.5,
      noOfReviews: 1400,
    },
    comapny_name: "NIke Air jordan Excee",
    current_price: 5208,
    original_price: 63025,
    discount: "60%",
  },
  {
    id: "08",
    item_image: "/images/shoe8.png",
    rating: {
      stars: 4.5,
      noOfReviews: 1400,
    },
    comapny_name: "NIke Air jordan Excee",
    current_price: 9662,
    original_price: 18520,
    discount: "60%",
  },
  {
    id: "09",
    item_image: "/images/shoe9.png",
    rating: {
      stars: 4.5,
      noOfReviews: 1400,
    },
    comapny_name: "NIke Air jordan Excee",
    current_price: 8520,
    original_price: 98745,
    discount: "60%",
  },
  {
    id: "10",
    item_image: "/images/shoe16.png",
    rating: {
      stars: 4.5,
      noOfReviews: "7k",
    },
    comapny_name: "NIke Air jordan Excee",
    current_price: 9632,
    original_price: 10258,
    discount: "60%",
  },
  {
    id: "11",
    item_image: "/images/shoe11.png",
    rating: {
      stars: 4.5,
      noOfReviews: "9k",
    },
    comapny_name: "NIke Air jordan Excee",
    current_price: 8745,
    original_price: 10256,
    discount: "60%",
  },
  {
    id: "12",
    item_image: "/images/shoe12.png",
    rating: {
      stars: 4.5,
      noOfReviews: 1400,
    },
    comapny_name: "NIke Air jordan Excee",
    current_price: 2058,
    original_price:5208,
    discount: "60%",
  },
  {
    id: "13",
    item_image: "/images/shoe13.png",
    rating: {
      stars: 4.5,
      noOfReviews: 1400,
    },
    comapny_name: "NIke Air jordan Excee",
    current_price: 2036,
    original_price: 4562,
    discount: "60%",
  },
  {
    id: "14",
    item_image: "/images/shoe14.png",
    rating: {
      stars: 4.5,
      noOfReviews: 1400,
    },
    comapny_name: "NIke Air jordan Excee",
    current_price: 3210,
    original_price: 6541,
    discount: "60%",
  },
  {
    id: "15",
    item_image: "/images/shoe15.png",
    rating: {
      stars: 4.5,
      noOfReviews: 1400,
    },
    comapny_name: "NIke Air jordan Excee",
    current_price: 6520,
    original_price: 12584,
    discount: "60%",
  },
  {
    id: "16",
    item_image: "/images/shoe16.png",
    rating: {
      stars: 5.0,
      noOfReviews: "8k",
    },
    comapny_name: "Nike basketball shoes",
    current_price:8569,
    original_price: 9520,
    discount: "20%",
  },
];
