let Womenitems = [
  {
    id: "01",
    item_image: "/images/womenshoe1.png",
    rating: {
      stars: 4.5,
      noOfReviews: "14k",
    },
    comapny_name: "NIke Air women Excee",
    current_price: "RS 7606",
    original_price: "RS 18405",
    discount: "60%",
  },
  {
    id: "02",
    item_image: "/images/womenshoe2.png",
    rating: {
      stars: 4.0,
      noOfReviews: "10k",
    },
    comapny_name: "Kine six fashion  Excee",
    current_price: "RS 8765",
    original_price: "RS 10405",
    discount: "40%",
  },
  {
    id: "03",
    item_image: "/images/womenshoe3.png",
    rating: {
      stars: 4.5,
      noOfReviews: "5k",
    },
    comapny_name: "NIke flex womenshoe  ",
    current_price: "RS 5246",
    original_price: "RS 7892",
    discount: "30%",
  },
  {
    id: "04",
    item_image: "/images/womenshoe4.png",
    rating: {
      stars: 4.5,
      noOfReviews: "8k",
    },
    comapny_name: "Addidas slider",
    current_price: "RS 2558",
    original_price: "RS 4563",
    discount: "60%",
  },
  {
    id: "05",
    item_image: "/images/womenshoe5.png",
    rating: {
      stars: 4.5,
      noOfReviews: "6k",
    },
    comapny_name: "NIke Air jordan Excee",
    current_price: "RS 8520 ",
    original_price: "RS 18405",
    discount: "50%",
  },
  {
    id: "06",
    item_image: "/images/womenshoe6.png",
    rating: {
      stars: 4.5,
      noOfReviews: "3k",
    },
    comapny_name: "NIke  jordan Air Excee",
    current_price: "RS 7606",
    original_price: "RS 18405",
    discount: "50%",
  },
  {
    id: "07",
    item_image: "/images/womenshoe7.jpeg",
    rating: {
      stars: 4.5,
      noOfReviews: 1400,
    },
    comapny_name: "NIke black top heels",
    current_price: "RS 203",
    original_price: "RS 18405",
    discount: "60%",
  },
  {
    id: "08",
    item_image: "/images/womenshoe8.jpeg",
    rating: {
      stars: 4.5,
      noOfReviews: 1400,
    },
    comapny_name: "NIke yellow sandles",
    current_price: "RS 7606",
    original_price: "RS 18405",
    discount: "60%",
  },
  {
    id: "09",
    item_image: "/images/womenshoe9.jpeg",
    rating: {
      stars: 4.5,
      noOfReviews: "5k",
    },
    comapny_name: "Bata walking shoes",
    current_price: "RS 7606",
    original_price: "RS 18405",
    discount: "60%",
  },
  {
    id: "10",
    item_image: "/images/womenshoe10.jpeg",
    rating: {
      stars: 4.5,
      noOfReviews: "7k",
    },
    comapny_name: "women sandles",
    current_price: "RS 7606",
    original_price: "RS 18405",
    discount: "60%",
  },
  {
    id: "11",
    item_image: "/images/womenshoe11.jpeg",
    rating: {
      stars: 4.5,
      noOfReviews: "9k",
    },
    comapny_name: "NIke Air jordan Excee",
    current_price: "RS 7606",
    original_price: "RS 18405",
    discount: "60%",
  },
  {
    id: "12",
    item_image: "/images/womenshoe12.jpeg",
    rating: {
      stars: 4.5,
      noOfReviews: 1400,
    },
    comapny_name: "NIke Air jordan Excee",
    current_price: "RS 7606",
    original_price: "RS 18405",
    discount: "60%",
  },
  {
    id: "13",
    item_image: "/images/womenshoe13.jpeg",
    rating: {
      stars: 4.5,
      noOfReviews: "2k",
    },
    comapny_name: "Kine bus sole",
    current_price: "RS 7606",
    original_price: "RS 18405",
    discount: "60%",
  },
  {
    id: "14",
    item_image: "/images/womenshoe14.webp",
    rating: {
      stars: 4.2,
      noOfReviews: "56k",
    },
    comapny_name: "Situll beautiful hills",
    current_price: "RS 25025",
    original_price: "RS 18405",
    discount: "60%",
  },
  {
    id: "15",
    item_image: "/images/shoe15.png",
    rating: {
      stars: 4.5,
      noOfReviews: "2k",
    },
    comapny_name: "Metro running shoes",
    current_price: "RS 5204",
    original_price: "RS 18405",
    discount: "60%",
  },
  {
    id: "16",
    item_image: "/images/shoe16.png",
    rating: {
      stars: 5.0,
      noOfReviews: "8k",
    },
    comapny_name: "Nike basketball shoes",
    current_price: "RS 8569",
    original_price: "RS 9520",
    discount: "20%",
  },
];
